"""Add tennis player and stats tables

Revision ID: 4f250935d34c
Revises: bd06843f94d5
Create Date: 2025-12-08 17:08:14.264150

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f250935d34c'
down_revision = 'bd06843f94d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elo_overall', sa.Integer(), nullable=True),
    sa.Column('elo_hard', sa.Integer(), nullable=True),
    sa.Column('elo_clay', sa.Integer(), nullable=True),
    sa.Column('elo_grass', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=True)
    op.create_table('playerstats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('surface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serve_1_in_pct', sa.Float(), nullable=False),
    sa.Column('serve_1_won_pct', sa.Float(), nullable=False),
    sa.Column('serve_2_won_pct', sa.Float(), nullable=False),
    sa.Column('ace_pct', sa.Float(), nullable=False),
    sa.Column('df_pct', sa.Float(), nullable=False),
    sa.Column('return_won_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstats_surface'), 'playerstats', ['surface'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerstats_surface'), table_name='playerstats')
    op.drop_table('playerstats')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
