"""Add Match model

Revision ID: bd06843f94d5
Revises: 1a31ce608336
Create Date: 2025-12-08 18:08:15.352986

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd06843f94d5'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player1_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player2_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('surface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('p1_odds', sa.Integer(), nullable=False),
    sa.Column('p2_odds', sa.Integer(), nullable=False),
    sa.Column('market_vig', sa.Float(), nullable=False),
    sa.Column('last_simulated_at', sa.DateTime(), nullable=True),
    sa.Column('sim_win_prob_p1', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
